all:
  # Standard editor values are tinyMCE / fckEditor. If you want to use another
  # editor you can call it as you want. If you want to use the rich function
  # leave the parameter blanc
  webeditor: tinyMCE
  
  # Path to images directory 
  images_path: %SF_WEB_DIR%/uploads/assets
  
  # Absolute path to images directory 
  absolute_images_path: '/uploads/assets/'
  
  # Configuration file for loading scripts
  w3s_scripts_dir: %SF_PLUGINS_DIR%/w3sCmsPlugin/config/w3s_scripts
  
  # Some useful paths to w3sCmsPlugin web directory
  w3s_web_images_dir: /w3sCmsPlugin/images
  w3s_web_js_dir: /w3sCmsPlugin/js
  w3s_web_themes_dir: %SF_ROOT_DIR%/themes
  w3s_web_published_dir: %SF_DATA_DIR%/published
  
  # The w3studioCms skin 
  w3s_web_window_skin_dir: %SF_W3S_WEB_CSS_DIR%/themes/window
  w3s_web_skin_dir: %SF_W3S_WEB_CSS_DIR%/themes/%SF_W3S_SKIN%
  w3s_web_skin_images_dir: %SF_W3S_WEB_CSS_DIR%/themes/%SF_W3S_SKIN%/images
  
  # Default META
  w3s_meta_title: 'A website powered by W3StudioCMS'
  w3s_meta_keywords: ''
  w3s_meta_description: ''
